version: "3.9"

services:
  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    hostname: reverse-proxy
    tty: true
    stdin_open: true
    restart: "unless-stopped"

    volumes:
      - 

    ports:
      - 8080:80
  api:
    build: .
