version: "3.9"

services:
  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    hostname: reverse-proxy
    tty: true
    stdin_open: true
    restart: "unless-stopped"

    volumes:
      - 

    ports:
      - 8080:80
  api:
    build: .


# services:
#   football-api:
#     tty: true
#     stdin_open: true
#     restart: "unless-stopped"
#     build:
#       dockerfile: Dockerfile
#       context: .
#       target: football-api
#       args:
#         - NODE_ENV=${NODE_ENV}
#         - FOOTBALL_ENV=${FOOTBALL_ENV}
#     hostname: football-api
#     ports:
#       - "4001-4005:4001"
#     env_file:
#       - .env
#     networks:
#       - football-network
#     secrets:
#       - database-secrets
#     depends_on:
#       - football-database
#   football-frontend:
#     container_name: football-frontend
#     tty: true
#     stdin_open: true
#     restart: "unless-stopped"
#     build:
#       dockerfile: Dockerfile
#       context: .
#       target: football-frontend
#       args:
#         - NODE_ENV=${NODE_ENV}
#         - FOOTBALL_ENV=${FOOTBALL_ENV}
#     hostname: football-frontend
#     ports:
#       - "8080:8080"
#     env_file:
#       - .env
#     networks:
#       - football-network
#   football-proxy:
#     container_name: football-proxy
#     build:
#       dockerfile: Dockerfile
#       context: .
#       target: football-proxy
#       args:
#         - NODE_ENV=${NODE_ENV}
#         - FOOTBALL_ENV=${FOOTBALL_ENV}
#     env_file:
#       - .env
#     tty: true
#     stdin_open: true
#     restart: "unless-stopped"
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#       - /var/www/certbot:/var/www/certbot
#       - etc/letsencrypt:/etc/letsencrypt
#       - /var/lib/letsencrypt:/var/lib/letsencrypt
#     depends_on:
#       - football-frontend
#       - football-api
#     links:
#       - football-frontend
#       - football-api
#     networks:
#       - football-network
#   football-database:
#     image: 'mongo'
#     container_name: football-database
#     hostname: football-database
#     tty: true
#     stdin_open: true
#     restart: "unless-stopped"
#     ports:
#       - 27017:27017
#     volumes:
#       - /var/lib/mongodb:/var/lib/mongodb
#       - /var/log/mongodb:/var/log/mongodb
#       - ./packages/database/config/mongod.conf:/etc/mongod.conf
#     networks:
#       - football-network
#     entrypoint: ["mongod","--config","/etc/mongod.conf"]
# networks:
#   football-network:
#     driver: bridge
# secrets:
#   database-secrets:
#     file: packages/database/.secrets
